services:
  customerapi:
    build:
      context: .
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Mongo__ConnectionStrings: mongodb://customer-service:customer-service@customerdb:27017
      Mongo__Database: customer-service
      Consul__Host: http://localhost:8500
      RabbitMQ__Host: crow-01.rmq.cloudamqp.com
      RabbitMQ__User: cnxoyvms
      RabbitMQ__Password: QlHhmVNnNeGL_s3rx9uAZ4icwcVBKo9I
      RabbitMQ__Port: 5672
      RabbitMQ__VirtualHost: cnxoyvms
      Urls: http://+:5002
    command: bash start-dev.sh
    ports:
      - "5002:5002"
    networks:
      - awesome-shop-services-net
    volumes:
      - .:/AwesomeShop.Services.Customers
    depends_on:
      - customerdb
  customerdb:
    image: mongodb/mongodb-community-server:7.0.5-ubi8
    environment:
      MONGO_INITDB_ROOT_USERNAME: customer-service
      MONGO_INITDB_ROOT_PASSWORD: customer-service
    ports:
      - "27017:27017"
    networks:
      - awesome-shop-services-net

networks:
  awesome-shop-services-net:
    name: awesome-shop-services-net
    external: true
